#ifndef __MAIN_H
#define __MAIN_H

#define MAIN_THREAD_ROM_SWAP_COMMAND    0x20000000   //b29
#define MAIN_THREAD_REQUEST_ADC_CONVERSION_COMMAND    0x10000000   //b28
#define MAIN_THREAD_COMMANDS_MASK	(MAIN_THREAD_ROM_SWAP_COMMAND | MAIN_THREAD_REQUEST_ADC_CONVERSION_COMMAND)
//#define MAIN_THREAD_COMMANDS_MASK	(MAIN_THREAD_ROM_SWAP_COMMAND)

// If your joystick can go from one extreme to the other then maybe use 0 to 255
//#define ADC_LOW_THRESHOLD 0
//#define ADC_HIGH_THRESHOLD 255

#define ADC_LOW_THRESHOLD 64
#define ADC_HIGH_THRESHOLD 192

#endif

