/*
  List rom files in here that you would like to compile in to
  the flash (firmware image) at build time. Just have one .incbin
  line after the label for the rom slot number.
*/

slot_4_base:
	//.incbin "roms/ESWMMFS.rom"
slot_5_base:
	//.incbin "roms/AP6v130ta.rom"
slot_6_base:
	//.incbin "roms/blank.rom"
slot_7_base:
	//.incbin "roms/blank.rom"
slot_12_base:
	//.incbin "roms/blank.rom"
slot_13_base:
	//.incbin "roms/blank.rom"
slot_14_base:
	//.incbin "roms/blank.rom"
slot_15_base:
	//.incbin "roms/blank.rom"
slots_end:
